function q = R2q(R)
% R2Q  Rotation matrix to quaternion
%
% Ref: Markley, "Attitude Determination Using Two Vectors Measurements",
% http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19990052720.pdf
%

    % find maximum of trace or diagonal element of R
    tra = trace(R);
    [mx, i] = max([R(1,1), R(2,2), R(3,3), tra]);
    
    % compute unnormalized quaternion
    if (i == 1)
        q = [R(2,3) - R(3,2);...
             2 * mx + 1 - tra;...
             R(1,2) + R(2,1);...
             R(1,3) + R(3,1)];
    elseif (i == 2)
        q = [R(3,1) - R(1,3);...
             R(2,1) + R(1,2);...
             2 * mx + 1 - tra;...
             R(2,3) + R(3,2)];
    elseif (i == 3)
        q = [R(1,2) - R(2,1);...
             R(3,1) + R(1,3);...
             R(3,2) + R(2,3);...
             2 * mx + 1 - tra];
    else % i == 4
        q = [1 + tra;...
             R(2,3) - R(3,2);...
             R(3,1) - R(1,3);...
             R(1,2) - R(2,1)];
    end

    % normalize the quaternion
    q = q / norm(q);

end
